// Code generated by MockGen. DO NOT EDIT.
// Source: llm.go
//
// Generated by this command:
//
//	mockgen -source=llm.go -destination=llmmock/client.go -package=llmmock Client
//

// Package llmmock is a generated GoMock package.
package llmmock

import (
	context "context"
	reflect "reflect"

	llm "github.com/jeon-jihyeon/nodloop/internal/llm"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Complete mocks base method.
func (m *MockClient) Complete(ctx context.Context, req llm.Request) (llm.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, req)
	ret0, _ := ret[0].(llm.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Complete indicates an expected call of Complete.
func (mr *MockClientMockRecorder) Complete(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockClient)(nil).Complete), ctx, req)
}
