package knowledge

import "errors"

var (
	ErrNotFound             = errors.New("knowledge: not found")
	ErrIDRequired           = errors.New("knowledge: id is required")
	ErrVersionInvalid       = errors.New("knowledge: version must be positive")
	ErrKindUnknown          = errors.New("knowledge: unknown kind")
	ErrContentRequired      = errors.New("knowledge: content is required")
	ErrEvidenceRequired     = errors.New("knowledge: at least one evidence reference is required")
	ErrBasisUnknown         = errors.New("knowledge: unknown basis")
	ErrStatusUnknown        = errors.New("knowledge: unknown status")
	ErrApproverRequired     = errors.New("knowledge: an approver is required")
	ErrAuthorRequired       = errors.New("knowledge: author is required")
	ErrTransitionInvalid    = errors.New("knowledge: invalid status transition")
	ErrVersionUnapproved    = errors.New("knowledge: version is not approved")
	ErrVetoKind             = errors.New("knowledge: only a judgment carries a veto")
	ErrVetoInvalid          = errors.New("knowledge: invalid veto")
	ErrVetoExample          = errors.New("knowledge: veto does not block its example")
	ErrFolderFull           = errors.New("knowledge: folder may outgrow the review")
	ErrExport               = errors.New("knowledge: approved knowledge was not exported")
	ErrCompactionInvalid    = errors.New("knowledge: invalid compaction")
	ErrCompactionIncomplete = errors.New("knowledge: incomplete compaction; propose again")
	ErrCompactionOverlap    = errors.New("knowledge: two new items of one kind share a folder")
	ErrCompactionVeto       = errors.New("knowledge: compaction would lift a veto")
	ErrCompactionOutdated   = errors.New("knowledge: an old item changed since the compaction was proposed")
	ErrCompactionPending    = errors.New("knowledge: another compaction of the same items is pending")
	ErrParagraphOnly        = errors.New("knowledge: item cites only procedure paragraphs and has nothing to replay")
	ErrReplayNotPassed      = errors.New("knowledge: the replay of the compaction has not passed")
	ErrNarrowInvalid        = errors.New("knowledge: narrowing needs a refuted change context")
	ErrNarrowExhausted      = errors.New("knowledge: narrowing would leave no change context of the version")
	ErrPromoteInvalid       = errors.New("knowledge: promotion needs a confirmed outcome")
	ErrPromoteVerified      = errors.New("knowledge: version is verified already")
	ErrScopeInvalid         = errors.New("knowledge: scope names no event")
	ErrScopeUnobserved      = errors.New("knowledge: scope names a value no event of the data set carries")
	ErrCandidateOutdated    = errors.New("knowledge: candidate was not built from the approved version it would replace")
	ErrVetoLifted           = errors.New("knowledge: new version would lift the veto of the approved version")
	ErrScopeWidened         = errors.New("knowledge: new version would reach events the approved version never reached")
	ErrImportStale          = errors.New("knowledge: import record is older than the recorded history of its version")
)
