// Code generated by MockGen. DO NOT EDIT.
// Source: classify.go
//
// Generated by this command:
//
//	mockgen -source=classify.go -destination=classifymock/classifier.go -package=classifymock Classifier
//

// Package classifymock is a generated GoMock package.
package classifymock

import (
	context "context"
	reflect "reflect"

	classify "github.com/jeon-jihyeon/nodloop/internal/classify"
	gomock "go.uber.org/mock/gomock"
)

// MockClassifier is a mock of Classifier interface.
type MockClassifier struct {
	ctrl     *gomock.Controller
	recorder *MockClassifierMockRecorder
	isgomock struct{}
}

// MockClassifierMockRecorder is the mock recorder for MockClassifier.
type MockClassifierMockRecorder struct {
	mock *MockClassifier
}

// NewMockClassifier creates a new mock instance.
func NewMockClassifier(ctrl *gomock.Controller) *MockClassifier {
	mock := &MockClassifier{ctrl: ctrl}
	mock.recorder = &MockClassifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClassifier) EXPECT() *MockClassifierMockRecorder {
	return m.recorder
}

// Classify mocks base method.
func (m *MockClassifier) Classify(ctx context.Context, req classify.Request) (classify.Answers, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Classify", ctx, req)
	ret0, _ := ret[0].(classify.Answers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Classify indicates an expected call of Classify.
func (mr *MockClassifierMockRecorder) Classify(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Classify", reflect.TypeOf((*MockClassifier)(nil).Classify), ctx, req)
}
