// Package file implements the knowledge store on one append only JSONL file
package file

import (
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"

	"github.com/jeon-jihyeon/nodloop/internal/atomicfile"
	"github.com/jeon-jihyeon/nodloop/internal/jsonl"
	"github.com/jeon-jihyeon/nodloop/internal/knowledge"
)

const (
	knowledgeFile = "knowledge.jsonl"
	// The approved knowledge as Claude Code rules that a CLAUDE.md imports
	rulesFile = "approved.md"
)

// The first line names the record directory so a reader of the import knows which ledger wrote it
const rulesLead = "<!-- Generated by nodloop from the approved knowledge of %s. " +
	"Edits here are overwritten. Retire the knowledge to remove a line -->\n" +
	"# Approved nodloop knowledge\n\n" +
	"Each line is a correction a person approved for the runs its scope fits. It never overrides what the user asks now\n"

type Store struct {
	file jsonl.File[knowledge.Knowledge]
	dir  string
}

func New(dir string) (*Store, error) {
	f, err := jsonl.Open[knowledge.Knowledge](dir, knowledgeFile)
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrOpen, err)
	}
	return &Store{file: f, dir: dir}, nil
}

// The rules file of the record directory dir
func RulesPath(dir string) string {
	return filepath.Join(dir, rulesFile)
}

func (s *Store) Append(_ context.Context, k knowledge.Knowledge) error {
	if err := s.file.Append(k); err != nil {
		return fmt.Errorf("%w: %w", ErrAppend, err)
	}
	return nil
}

// decide gets the records newest first as List gives them and its records land in their order
// Its refusal comes back as it is and only a file failure becomes ErrAppend so a caller can tell the two apart
func (s *Store) AppendDecided(_ context.Context, decide func(all knowledge.Set) ([]knowledge.Knowledge, error)) error {
	var refused error
	err := s.file.AppendDecided(func(current []knowledge.Knowledge) ([]knowledge.Knowledge, error) {
		records, err := decide(newestFirst(current))
		refused = err
		return records, err
	})
	switch {
	case err == nil:
		return nil
	case refused != nil:
		return refused
	}
	return fmt.Errorf("%w: %w", ErrAppend, err)
}

// Rewrites the rules file under the append lock with the header and what render returns
// 1. an empty render while no rules file exists writes nothing so an unused feature leaves nothing on disk
// 2. once written an empty render keeps a header only file so an import never points at a missing file
// 3. the bytes replace the file in one rename so a session never reads half of it
func (s *Store) ReplaceRules(_ context.Context, render func(all knowledge.Set) string) error {
	path := RulesPath(s.dir)
	err := s.file.AppendDecided(func(current []knowledge.Knowledge) ([]knowledge.Knowledge, error) {
		body := render(newestFirst(current))
		if _, err := os.Lstat(path); body == "" && errors.Is(err, os.ErrNotExist) {
			return nil, nil
		}
		return nil, atomicfile.Replace(path, []byte(fmt.Sprintf(rulesLead, s.dir)+body))
	})
	if err != nil {
		return fmt.Errorf("%w: %w", ErrWrite, err)
	}
	return nil
}

func (s *Store) List(_ context.Context) ([]knowledge.Knowledge, error) {
	records, err := s.file.All()
	if err != nil {
		return nil, fmt.Errorf("%w: %w", ErrRead, err)
	}
	return newestFirst(records), nil
}

// The records of the file in the reverse of file order
func newestFirst(records []knowledge.Knowledge) knowledge.Set {
	all := slices.Clone(records)
	slices.Reverse(all)
	return all
}
