package file_test

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"io/fs"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/jeon-jihyeon/nodloop/internal/veto"
	"github.com/jeon-jihyeon/nodloop/internal/veto/file"
)

func TestApprovedFileReplace(t *testing.T) {
	t.Parallel()
	disabled := false
	spec := veto.Spec{
		ID: "k1", Tool: "Bash", When: []veto.When{{Field: "command", Match: `sed\s+-i`, Unless: "dry"}},
		Reason: "never edit files with sed -i", Source: "nodloop knowledge k1 v1 approved by jed", Enabled: &disabled,
	}
	written := "# Generated by nodloop from the approved judgment knowledge of /records\n" +
		"# Edits here are overwritten. Retire the knowledge to remove a veto\n" +
		"vetoes:\n" +
		"    - id: k1\n" +
		"      tool: Bash\n" +
		"      when:\n" +
		"        - field: command\n" +
		"          match: sed\\s+-i\n" +
		"          unless: dry\n" +
		"      reason: never edit files with sed -i\n" +
		"      source: nodloop knowledge k1 v1 approved by jed\n" +
		"      enabled: false\n"
	parsed, err := spec.Veto()
	require.NoError(t, err)
	type args struct {
		// Files under home before the write keyed by relative path
		// {approved} is the approved file of /records
		files map[string]string
		// Directories under home before the write
		dirs  []string
		specs []veto.Spec
		// Returned by the read in place of the specs
		readErr error
		// Record directories an older build named approved files after
		// Each file holds one veto and an empty one has no header line
		spellings []string
	}
	type want struct {
		// Empty means no file
		content string
		// What veto.Parse reads back from the file
		vetoes veto.Vetoes
		err    error
		// Spellings whose file is still there
		kept []string
	}
	tcs := []struct {
		name string
		args args
		want want
	}{
		{
			"specs are written as a file guard reads back",
			args{specs: []veto.Spec{spec}},
			want{written, veto.Vetoes{parsed}, nil, nil},
		},
		{
			"specs replace an older file whole",
			args{files: map[string]string{"{approved}": "vetoes: []\n"}, specs: []veto.Spec{spec}},
			want{written, veto.Vetoes{parsed}, nil, nil},
		},
		{"no specs remove the file", args{files: map[string]string{"{approved}": written}}, want{"", veto.Vetoes{}, nil, nil}},
		{"no specs and no file leave no approved file", args{}, want{"", veto.Vetoes{}, nil, nil}},
		{
			"a failed read keeps the file as it was",
			args{files: map[string]string{"{approved}": written}, specs: []veto.Spec{}, readErr: assert.AnError},
			want{written, veto.Vetoes{parsed}, assert.AnError, nil},
		},
		{
			"files of other spellings of the record directory are removed after the write",
			args{specs: []veto.Spec{spec}, spellings: []string{"/records/", "/records/./"}},
			want{written, veto.Vetoes{parsed}, nil, nil},
		},
		{
			"a retire removes the file of a trailing slash spelling",
			args{spellings: []string{"/records/"}},
			want{"", veto.Vetoes{}, nil, nil},
		},
		{
			"files of another record directory stay",
			args{specs: []veto.Spec{spec}, spellings: []string{"/other", "/records/sub"}},
			want{written, veto.Vetoes{parsed}, nil, []string{"/other", "/records/sub"}},
		},
		{
			"a relative spelling stays because its directory is unknown",
			args{spellings: []string{"records"}},
			want{"", veto.Vetoes{}, nil, []string{"records"}},
		},
		{
			"a file without a header stays",
			args{spellings: []string{""}},
			want{"", veto.Vetoes{}, nil, []string{""}},
		},
		{
			"a failed read keeps the file of another spelling",
			args{specs: []veto.Spec{spec}, readErr: assert.AnError, spellings: []string{"/records/"}},
			want{"", veto.Vetoes{}, assert.AnError, []string{"/records/"}},
		},
		{
			"a file in place of the directory fails",
			args{files: map[string]string{".claude/nodloop": ""}, specs: []veto.Spec{spec}},
			want{"", veto.Vetoes{}, file.ErrWrite, nil},
		},
		{
			"a directory in place of the file cannot be removed",
			args{dirs: []string{"{approved}/kept"}},
			want{"", veto.Vetoes{}, file.ErrWrite, nil},
		},
		{
			"a directory in place of the file cannot be replaced",
			args{dirs: []string{"{approved}/kept"}, specs: []veto.Spec{spec}},
			want{"", veto.Vetoes{}, file.ErrWrite, nil},
		},
	}
	for _, tc := range tcs {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			home := t.TempDir()
			f := file.NewApprovedFile(home, "/records")
			approved, err := filepath.Rel(home, f.Path())
			require.NoError(t, err)
			r := strings.NewReplacer("{approved}", approved)
			for rel, content := range tc.args.files {
				path := filepath.Join(home, r.Replace(rel))
				require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o700))
				require.NoError(t, os.WriteFile(path, []byte(content), 0o600))
			}
			for _, rel := range tc.args.dirs {
				require.NoError(t, os.MkdirAll(filepath.Join(home, r.Replace(rel)), 0o700))
			}
			for _, spelling := range tc.args.spellings {
				content := "vetoes: [{id: old, tool: Bash, when: [{field: command, match: x}], reason: r}]\n"
				if spelling != "" {
					content = "# Generated by nodloop from the approved judgment knowledge of " + spelling + "\n" + content
				}
				path := olderPath(home, spelling)
				require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o700))
				require.NoError(t, os.WriteFile(path, []byte(content), 0o600))
			}

			err = f.Replace(func() ([]veto.Spec, error) { return tc.args.specs, tc.args.readErr })

			assert.ErrorIs(t, err, tc.want.err)
			// A missing file and a directory read as empty
			got, _ := os.ReadFile(f.Path())
			assert.Equal(t, tc.want.content, string(got))
			vetoes, err := veto.Parse(got)
			require.NoError(t, err)
			assert.Equal(t, tc.want.vetoes, vetoes)
			var kept []string
			for _, spelling := range tc.args.spellings {
				if _, err := os.Stat(olderPath(home, spelling)); err == nil {
					kept = append(kept, spelling)
				}
			}
			assert.Equal(t, tc.want.kept, kept)
		})
	}
}

// The paths under home after a replace show whether it created or locked anything
func TestApprovedFileReplaceOnAnUntouchedHome(t *testing.T) {
	t.Parallel()
	spec := veto.Spec{ID: "k1", Tool: "Bash", When: []veto.When{{Field: "command", Match: `sed\s+-i`}}, Reason: "r"}
	const (
		approved = ".claude/nodloop/vetoes.approved.e7024ac054e4.yaml"
		// Written by an older build for the trailing slash spelling of /records
		spelled = ".claude/nodloop/vetoes.approved.5c4484167a35.yaml"
	)
	type args struct {
		// Files under home before the write keyed by relative path
		files map[string]string
		// A directory under home made read only before the write
		readOnly string
		specs    []veto.Spec
		readErr  error
	}
	type want struct {
		err error
		// Every path under home after the write
		paths []string
	}
	tcs := []struct {
		name string
		args args
		want want
	}{
		{"an empty read on a fresh home creates nothing", args{}, want{nil, nil}},
		{
			"an empty read under a read only claude directory succeeds",
			args{readOnly: ".claude"},
			want{nil, []string{".claude"}},
		},
		{
			"an empty read after an earlier veto keeps the lock",
			args{files: map[string]string{approved + ".lock": ""}},
			want{nil, []string{".claude", ".claude/nodloop", approved + ".lock"}},
		},
		{
			"an empty read removes a file an unlocked older build wrote",
			args{files: map[string]string{approved: "vetoes: []\n"}},
			want{nil, []string{".claude", ".claude/nodloop", approved + ".lock"}},
		},
		{
			"an empty read removes the file of an older spelling",
			args{files: map[string]string{
				spelled: "# Generated by nodloop from the approved judgment knowledge of /records/\nvetoes: []\n",
			}},
			want{nil, []string{".claude", ".claude/nodloop", approved + ".lock"}},
		},
		{
			"a first veto writes the file and the lock",
			args{specs: []veto.Spec{spec}},
			want{nil, []string{".claude", ".claude/nodloop", approved, approved + ".lock"}},
		},
		{"a failed read on a fresh home creates nothing", args{readErr: assert.AnError}, want{assert.AnError, nil}},
	}
	for _, tc := range tcs {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			home := t.TempDir()
			for rel, content := range tc.args.files {
				path := filepath.Join(home, rel)
				require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o700))
				require.NoError(t, os.WriteFile(path, []byte(content), 0o600))
			}
			if tc.args.readOnly != "" {
				if runtime.GOOS == "windows" || os.Geteuid() == 0 {
					t.Skip("the mode does not stop this user from writing")
				}
				ro := filepath.Join(home, tc.args.readOnly)
				require.NoError(t, os.MkdirAll(ro, 0o700))
				require.NoError(t, os.Chmod(ro, 0o555))
				t.Cleanup(func() { _ = os.Chmod(ro, 0o700) })
			}
			f := file.NewApprovedFile(home, "/records")
			require.Equal(t, filepath.Join(home, approved), f.Path())

			err := f.Replace(func() ([]veto.Spec, error) { return tc.args.specs, tc.args.readErr })

			assert.ErrorIs(t, err, tc.want.err)
			var paths []string
			require.NoError(t, filepath.WalkDir(home, func(path string, _ fs.DirEntry, err error) error {
				if err != nil || path == home {
					return err
				}
				rel, err := filepath.Rel(home, path)
				paths = append(paths, filepath.ToSlash(rel))
				return err
			}))
			assert.Equal(t, tc.want.paths, paths)
		})
	}
}

func TestNewApprovedFile(t *testing.T) {
	t.Parallel()
	type args struct {
		home      string
		recordDir string
	}
	tcs := []struct {
		name string
		args args
		want string
	}{
		{
			"the name carries the record directory",
			args{"/home/me", "/records"},
			"/home/me/.claude/nodloop/vetoes.approved.e7024ac054e4.yaml",
		},
		{
			"another record directory gets another file",
			args{"/home/me", "/other"},
			"/home/me/.claude/nodloop/vetoes.approved.bf2faee25960.yaml",
		},
		{"no home gives no path", args{"", "/records"}, ""},
	}
	for _, tc := range tcs {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			assert.Equal(t, tc.want, file.NewApprovedFile(tc.args.home, tc.args.recordDir).Path())
		})
	}
}

// The approved file an older build named after the record directory as spelled
func olderPath(home, spelling string) string {
	sum := sha256.Sum256([]byte(spelling))
	return filepath.Join(home, ".claude", "nodloop", "vetoes.approved."+hex.EncodeToString(sum[:6])+".yaml")
}

// Spellings of one record directory share one file and a replace through one removes the file an older build wrote for another
func TestApprovedFileSpellings(t *testing.T) {
	t.Parallel()
	spec := veto.Spec{ID: "k1", Tool: "Bash", When: []veto.When{{Field: "command", Match: `sed\s+-i`}}, Reason: "r"}
	type args struct {
		// Both relative to a root holding the directories rec and other and the symlink link to rec
		spelling string
		replacer string
	}
	tcs := []struct {
		name string
		args args
		want bool
	}{
		{"a symlink to the record directory is the same directory", args{"link", "rec"}, true},
		{"a directory not made yet below a symlink is the same as below its target", args{"link/new", "rec/new"}, true},
		{"another directory is another ledger", args{"other", "rec"}, false},
	}
	for _, tc := range tcs {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			root, home := t.TempDir(), t.TempDir()
			require.NoError(t, os.Mkdir(filepath.Join(root, "rec"), 0o700))
			require.NoError(t, os.Mkdir(filepath.Join(root, "other"), 0o700))
			require.NoError(t, os.Symlink(filepath.Join(root, "rec"), filepath.Join(root, "link")))
			spelled := filepath.Join(root, tc.args.spelling)
			older := olderPath(home, spelled)
			require.NoError(t, os.MkdirAll(filepath.Dir(older), 0o700))
			header := "# Generated by nodloop from the approved judgment knowledge of " + spelled + "\n"
			require.NoError(t, os.WriteFile(older, []byte(header+"vetoes: []\n"), 0o600))
			f := file.NewApprovedFile(home, filepath.Join(root, tc.args.replacer))

			err := f.Replace(func() ([]veto.Spec, error) { return []veto.Spec{spec}, nil })

			require.NoError(t, err)
			assert.Equal(t, tc.want, file.NewApprovedFile(home, spelled).Path() == f.Path())
			_, err = os.Stat(older)
			assert.Equal(t, tc.want, errors.Is(err, os.ErrNotExist))
		})
	}
}

// Without a home the relative path would land in the working directory
func TestApprovedFileWithoutHome(t *testing.T) {
	cwd := t.TempDir()
	t.Chdir(cwd)

	read := false
	err := file.NewApprovedFile("", "/records").Replace(func() ([]veto.Spec, error) {
		read = true
		return []veto.Spec{{ID: "k1"}}, nil
	})

	assert.NoError(t, err)
	assert.False(t, read, "nothing is read when nothing can be written")
	entries, err := os.ReadDir(cwd)
	require.NoError(t, err)
	assert.Empty(t, entries)
}

// A file of one producer holds only the vetoes that producer approved
func TestApprovedFileOf(t *testing.T) {
	home := t.TempDir()
	specs := []veto.Spec{
		{ID: "mine", Tool: "Bash", When: []veto.When{{Field: "command", Match: "rm"}}, Reason: "no rm", Producer: "session"},
		{ID: "theirs", Tool: "bash", When: []veto.When{{Field: "command", Match: "rm"}}, Reason: "no rm", Producer: "support-bot"},
	}
	f := file.NewApprovedFile(home, "/records").Of("session")

	require.NoError(t, f.Replace(func() ([]veto.Spec, error) { return specs, nil }))

	sources, err := file.Discover(t.TempDir(), home)
	require.NoError(t, err)
	var ids []string
	for _, v := range sources.Vetoes() {
		ids = append(ids, v.ID())
	}
	assert.Equal(t, []string{"mine"}, ids)
	written, err := os.ReadFile(f.Path())
	require.NoError(t, err)
	assert.NotContains(t, string(written), "support-bot", "the producer stays out of the file")
}
