package file_test

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/jeon-jihyeon/nodloop/internal/veto"
	"github.com/jeon-jihyeon/nodloop/internal/veto/file"
)

func TestApprovedFileWrite(t *testing.T) {
	t.Parallel()
	disabled := false
	spec := veto.Spec{
		ID: "k1", Tool: "Bash", When: []veto.When{{Field: "command", Match: `sed\s+-i`, Unless: "dry"}},
		Reason: "never edit files with sed -i", Source: "nodloop knowledge k1 v1 approved by jed", Enabled: &disabled,
	}
	written := "# Generated by nodloop from the approved judgment knowledge of /records\n" +
		"# Edits here are overwritten. Retire the knowledge to remove a veto\n" +
		"vetoes:\n" +
		"    - id: k1\n" +
		"      tool: Bash\n" +
		"      when:\n" +
		"        - field: command\n" +
		"          match: sed\\s+-i\n" +
		"          unless: dry\n" +
		"      reason: never edit files with sed -i\n" +
		"      source: nodloop knowledge k1 v1 approved by jed\n" +
		"      enabled: false\n"
	parsed, err := spec.Veto()
	require.NoError(t, err)
	type args struct {
		// Files under home before the write keyed by relative path
		// {approved} is the approved file of /records
		files map[string]string
		// Directories under home before the write
		dirs  []string
		specs []veto.Spec
	}
	type want struct {
		// Empty means no file
		content string
		// What veto.Parse reads back from the file
		vetoes veto.Vetoes
		err    error
	}
	tcs := []struct {
		name string
		args args
		want want
	}{
		{
			"specs are written as a file guard reads back",
			args{specs: []veto.Spec{spec}},
			want{written, veto.Vetoes{parsed}, nil},
		},
		{
			"specs replace an older file whole",
			args{files: map[string]string{"{approved}": "vetoes: []\n"}, specs: []veto.Spec{spec}},
			want{written, veto.Vetoes{parsed}, nil},
		},
		{"no specs remove the file", args{files: map[string]string{"{approved}": written}}, want{"", veto.Vetoes{}, nil}},
		{"no specs and no file leave nothing", args{}, want{"", veto.Vetoes{}, nil}},
		{
			"a file in place of the directory fails",
			args{files: map[string]string{".claude/nodloop": ""}, specs: []veto.Spec{spec}},
			want{"", veto.Vetoes{}, file.ErrWrite},
		},
		{
			"a directory in place of the file cannot be removed",
			args{dirs: []string{"{approved}/kept"}},
			want{"", veto.Vetoes{}, file.ErrWrite},
		},
		{
			"a directory in place of the file cannot be replaced",
			args{dirs: []string{"{approved}/kept"}, specs: []veto.Spec{spec}},
			want{"", veto.Vetoes{}, file.ErrWrite},
		},
	}
	for _, tc := range tcs {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			home := t.TempDir()
			f := file.NewApprovedFile(home, "/records")
			approved, err := filepath.Rel(home, f.Path())
			require.NoError(t, err)
			r := strings.NewReplacer("{approved}", approved)
			for rel, content := range tc.args.files {
				path := filepath.Join(home, r.Replace(rel))
				require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o700))
				require.NoError(t, os.WriteFile(path, []byte(content), 0o600))
			}
			for _, rel := range tc.args.dirs {
				require.NoError(t, os.MkdirAll(filepath.Join(home, r.Replace(rel)), 0o700))
			}

			err = f.Write(tc.args.specs)

			assert.ErrorIs(t, err, tc.want.err)
			// A missing file and a directory read as empty
			got, _ := os.ReadFile(f.Path())
			assert.Equal(t, tc.want.content, string(got))
			vetoes, err := veto.Parse(got)
			require.NoError(t, err)
			assert.Equal(t, tc.want.vetoes, vetoes)
		})
	}
}

func TestNewApprovedFile(t *testing.T) {
	t.Parallel()
	type args struct {
		home      string
		recordDir string
	}
	tcs := []struct {
		name string
		args args
		want string
	}{
		{
			"the name carries the record directory",
			args{"/home/me", "/records"},
			"/home/me/.claude/nodloop/vetoes.approved.e7024ac054e4.yaml",
		},
		{
			"another record directory gets another file",
			args{"/home/me", "/other"},
			"/home/me/.claude/nodloop/vetoes.approved.bf2faee25960.yaml",
		},
		{"no home gives no path", args{"", "/records"}, ""},
	}
	for _, tc := range tcs {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			assert.Equal(t, tc.want, file.NewApprovedFile(tc.args.home, tc.args.recordDir).Path())
		})
	}
}

// Without a home the relative path would land in the working directory
func TestApprovedFileWithoutHome(t *testing.T) {
	cwd := t.TempDir()
	t.Chdir(cwd)

	err := file.NewApprovedFile("", "/records").Write([]veto.Spec{{ID: "k1"}})

	assert.NoError(t, err)
	entries, err := os.ReadDir(cwd)
	require.NoError(t, err)
	assert.Empty(t, entries)
}
