package file

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"go.yaml.in/yaml/v3"

	"github.com/jeon-jihyeon/nodloop/internal/veto"
)

// Where every veto file lives relative to cwd or home
const dir = ".claude/nodloop"

// Approved files are named per record directory so one ledger never rewrites the vetoes of another
// `vetoes.approved.<12 hex of the record directory>.yaml`
const (
	approvedPrefix = "vetoes.approved."
	approvedSuffix = ".yaml"
)

const approvedHeader = "# Generated by nodloop from the approved judgment knowledge of %s\n" +
	"# Edits here are overwritten. Retire the knowledge to remove a veto\n"

// The generated veto file of one record directory under one home
type ApprovedFile struct {
	// Empty without a home
	path      string
	recordDir string
}

func NewApprovedFile(home, recordDir string) *ApprovedFile {
	if home == "" {
		return &ApprovedFile{}
	}
	sum := sha256.Sum256([]byte(recordDir))
	name := approvedPrefix + hex.EncodeToString(sum[:6]) + approvedSuffix
	return &ApprovedFile{path: filepath.Join(home, dir, name), recordDir: recordDir}
}

// Empty without a home
func (f *ApprovedFile) Path() string {
	return f.path
}

// Replaces the file with specs
// 1. without a home nothing is written because Discover reads no approved file there either
// 2. no specs removes the file so an unused feature leaves nothing on disk
// 3. the bytes go to a synced temp file renamed over the old one so guard never reads half a file
// Two processes that change statuses at once may leave the older set until the next status change
func (f *ApprovedFile) Write(specs []veto.Spec) error {
	if f.path == "" {
		return nil
	}
	if len(specs) == 0 {
		if err := os.Remove(f.path); err != nil && !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("%s: %w: %w", f.path, ErrWrite, err)
		}
		return nil
	}
	// A document of strings and a bool pointer always encodes
	body, _ := yaml.Marshal(document{Vetoes: specs})
	if err := f.replace(append(fmt.Appendf(nil, approvedHeader, f.recordDir), body...)); err != nil {
		return fmt.Errorf("%s: %w: %w", f.path, ErrWrite, err)
	}
	return nil
}

// The shape veto.Parse reads back
type document struct {
	Vetoes []veto.Spec `yaml:"vetoes"`
}

func (f *ApprovedFile) replace(b []byte) (err error) {
	if err = os.MkdirAll(filepath.Dir(f.path), 0o700); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(f.path), ".vetoes-*.yaml")
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			_ = os.Remove(tmp.Name())
		}
	}()
	if _, err = tmp.Write(b); err != nil {
		return errors.Join(err, tmp.Close())
	}
	if err = tmp.Sync(); err != nil {
		return errors.Join(err, tmp.Close())
	}
	if err = tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), f.path)
}

// Paths of every approved file under home in name order
// A missing directory holds none
func approvedPaths(home string) ([]string, error) {
	entries, err := os.ReadDir(filepath.Join(home, dir))
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("%s: %w: %w", filepath.Join(home, dir), ErrRead, err)
	}
	var paths []string
	for _, e := range entries {
		if strings.HasPrefix(e.Name(), approvedPrefix) && strings.HasSuffix(e.Name(), approvedSuffix) {
			paths = append(paths, filepath.Join(home, dir, e.Name()))
		}
	}
	return paths, nil
}
