package file

import (
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"go.yaml.in/yaml/v3"

	"github.com/jeon-jihyeon/nodloop/internal/veto"
)

// Where every veto file lives relative to cwd or home
const dir = ".claude/nodloop"

// Approved files are named per record directory so one ledger never rewrites the vetoes of another
// `vetoes.approved.<12 hex of the record directory>.yaml`
const (
	approvedPrefix = "vetoes.approved."
	approvedSuffix = ".yaml"
	// Beside the approved file and never read as vetoes because the name does not end in the approved suffix
	lockSuffix = ".lock"
)

// The first line names the record directory so a later write finds the files an older spelling of it left
const (
	approvedLead = "# Generated by nodloop from the approved judgment knowledge of "
	approvedNote = "# Edits here are overwritten. Retire the knowledge to remove a veto\n"
)

// The generated veto file of one record directory under one home
type ApprovedFile struct {
	// Empty without a home
	path      string
	recordDir string
	// The producer whose approved vetoes the file holds and every producer when empty
	producer string
}

// The same file holding only the approved vetoes of the producer
// Claude Code reads the file for its own tool calls so the vetoes another producer approved stay out of it
func (f *ApprovedFile) Of(producer string) *ApprovedFile {
	out := *f
	out.producer = producer
	return &out
}

// The specs of the producer of the file
func (f *ApprovedFile) mine(specs []veto.Spec) []veto.Spec {
	if f.producer == "" {
		return specs
	}
	return slices.DeleteFunc(slices.Clone(specs), func(s veto.Spec) bool { return s.Producer != f.producer })
}

// Two spellings of one record directory such as a symlinked path name one file and one lock
func NewApprovedFile(home, recordDir string) *ApprovedFile {
	if home == "" {
		return &ApprovedFile{}
	}
	recordDir = resolved(recordDir)
	sum := sha256.Sum256([]byte(recordDir))
	name := approvedPrefix + hex.EncodeToString(sum[:6]) + approvedSuffix
	return &ApprovedFile{path: filepath.Join(home, dir, name), recordDir: recordDir}
}

// Empty without a home
func (f *ApprovedFile) Path() string {
	return f.path
}

// Replaces the file with the specs read under an exclusive lock
// 1. without a home nothing is written and read is never called because Discover reads no approved file there either
// 2. read runs under the lock so of two processes replacing at once the later one reads the newer records and renames last
// 3. while this ledger left nothing under the home an empty read creates nothing so an unused feature leaves nothing on disk
// 4. otherwise no specs removes the file and the lock file stays beside it
// 5. the bytes go to a synced temp file renamed over the old one so guard never reads half a file
// 6. after the write the files another spelling of the same record directory wrote are removed so a retired veto there stops blocking
// A read error is returned as it is and keeps every file
// The read without the lock in item 3 only decides whether to lock and is never written
// A writer holding an older set made its lock file before its read and so before the caller appended the newer records
func (f *ApprovedFile) Replace(read func() ([]veto.Spec, error)) (err error) {
	if f.path == "" {
		return nil
	}
	if f.untouched() {
		specs, err := read()
		if err != nil {
			return err
		}
		if len(f.mine(specs)) == 0 {
			return nil
		}
	}
	if err := os.MkdirAll(filepath.Dir(f.path), 0o700); err != nil {
		return fmt.Errorf("%s: %w: %w", f.path, ErrWrite, err)
	}
	held, err := os.OpenFile(f.path+lockSuffix, os.O_CREATE|os.O_RDWR, 0o600)
	if err != nil {
		return fmt.Errorf("%s: %w: %w", f.path, ErrWrite, err)
	}
	defer func() { err = errors.Join(err, held.Close()) }()
	if err := lock(held); err != nil {
		return fmt.Errorf("%s: %w: %w", f.path, ErrWrite, err)
	}
	specs, err := read()
	if err != nil {
		return err
	}
	if err := f.write(f.mine(specs)); err != nil {
		return err
	}
	return f.removeSpellings()
}

// Whether this ledger never wrote under the home
// 1. no lock file beside the approved file
// 2. no approved file which an unlocked older build may have written
// 3. no approved file of another spelling of the record directory
// Any error other than a missing path counts as written so the locked path reports it
func (f *ApprovedFile) untouched() bool {
	for _, path := range []string{f.path + lockSuffix, f.path} {
		if _, err := os.Lstat(path); !errors.Is(err, os.ErrNotExist) {
			return false
		}
	}
	paths, err := approvedPaths(filepath.Dir(f.path))
	if err != nil {
		return false
	}
	for _, path := range paths {
		if f.spelledBy(approvedRecordDir(path)) {
			return false
		}
	}
	return true
}

// Removes the approved files an older spelling of the same record directory wrote
// 1. a file is the same ledger only when its first line names an absolute directory that resolves to this one
// 2. a relative or missing name is kept because the directory it meant is unknown and removing it could drop vetoes of another ledger
// 3. a file that cannot be read is kept so an unrelated file never fails the write
// 4. the lock files beside them stay because another process may hold one
// The ledger read has just written every approved veto so the removed files lose none that is still approved
func (f *ApprovedFile) removeSpellings() error {
	paths, err := approvedPaths(filepath.Dir(f.path))
	if err != nil {
		return err
	}
	var errs []error
	for _, path := range paths {
		if path == f.path || !f.spelledBy(approvedRecordDir(path)) {
			continue
		}
		if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
			errs = append(errs, fmt.Errorf("%s: %w: %w", path, ErrWrite, err))
		}
	}
	return errors.Join(errs...)
}

// Whether recordDir is another spelling of the record directory of this file
func (f *ApprovedFile) spelledBy(recordDir string) bool {
	return filepath.IsAbs(recordDir) && resolved(recordDir) == f.recordDir
}

// The absolute directory with every symlink of its existing part resolved
// 1. the part that does not exist yet is kept as written so a directory made later resolves to the same path
// 2. a relative directory is kept as written because it never names another spelling
func resolved(dir string) string {
	if !filepath.IsAbs(dir) {
		return dir
	}
	dir = filepath.Clean(dir)
	rest := ""
	for existing := dir; ; existing = filepath.Dir(existing) {
		if target, err := filepath.EvalSymlinks(existing); err == nil {
			return filepath.Join(target, rest)
		}
		if filepath.Dir(existing) == existing {
			return dir
		}
		rest = filepath.Join(filepath.Base(existing), rest)
	}
}

func (f *ApprovedFile) write(specs []veto.Spec) error {
	if len(specs) == 0 {
		if err := os.Remove(f.path); err != nil && !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("%s: %w: %w", f.path, ErrWrite, err)
		}
		return nil
	}
	// A document of strings and a bool pointer always encodes
	body, _ := yaml.Marshal(document{Vetoes: specs})
	if err := f.replace(append([]byte(approvedLead+f.recordDir+"\n"+approvedNote), body...)); err != nil {
		return fmt.Errorf("%s: %w: %w", f.path, ErrWrite, err)
	}
	return nil
}

// The shape veto.Parse reads back
type document struct {
	Vetoes []veto.Spec `yaml:"vetoes"`
}

func (f *ApprovedFile) replace(b []byte) (err error) {
	tmp, err := os.CreateTemp(filepath.Dir(f.path), ".vetoes-*.yaml")
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			_ = os.Remove(tmp.Name())
		}
	}()
	if _, err = tmp.Write(b); err != nil {
		return errors.Join(err, tmp.Close())
	}
	if err = tmp.Sync(); err != nil {
		return errors.Join(err, tmp.Close())
	}
	if err = tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmp.Name(), f.path)
}

// Paths of every approved file in folder in name order
// A missing folder holds none
func approvedPaths(folder string) ([]string, error) {
	entries, err := os.ReadDir(folder)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("%s: %w: %w", folder, ErrRead, err)
	}
	var paths []string
	for _, e := range entries {
		if approvedName(e.Name()) {
			paths = append(paths, filepath.Join(folder, e.Name()))
		}
	}
	return paths, nil
}

// The record directory the first line of an approved file names
// Empty when the file cannot be read or has no such line
func approvedRecordDir(path string) string {
	b, err := os.ReadFile(path)
	if err != nil {
		return ""
	}
	line, _, _ := strings.Cut(string(b), "\n")
	recordDir, found := strings.CutPrefix(line, approvedLead)
	if !found {
		return ""
	}
	return recordDir
}

func approvedName(name string) bool {
	return strings.HasPrefix(name, approvedPrefix) && strings.HasSuffix(name, approvedSuffix)
}
