package file_test

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/jeon-jihyeon/nodloop/internal/veto"
	"github.com/jeon-jihyeon/nodloop/internal/veto/file"
)

func TestSourcesVetoes(t *testing.T) {
	condition, err := veto.NewCondition("command", "x", "")
	require.NoError(t, err)
	when := []veto.Condition{condition}
	projectShared, err := veto.New("shared", "Bash", when, "project", true)
	require.NoError(t, err)
	projectOnly, err := veto.New("project-only", "Bash", when, "project", true)
	require.NoError(t, err)
	userShared, err := veto.New("shared", "Bash", when, "user", true)
	require.NoError(t, err)
	userOnly, err := veto.New("user-only", "Bash", when, "user", true)
	require.NoError(t, err)
	tcs := []struct {
		name string
		args file.Sources
		want veto.Vetoes
	}{
		{
			"earlier source wins on a shared id",
			file.Sources{
				{Path: "project", Vetoes: veto.Vetoes{projectShared, projectOnly}},
				{Path: "user", Vetoes: veto.Vetoes{userShared, userOnly}},
			},
			veto.Vetoes{projectShared, projectOnly, userOnly},
		},
		{"no sources merge to nothing", nil, nil},
	}
	for _, tc := range tcs {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			assert.Equal(t, tc.want, tc.args.Vetoes())
		})
	}
}

// Discover loads the file of a relative record directory without an error so the hook never fails on it
func TestSourceOrphan(t *testing.T) {
	entry := "vetoes: [{id: old, tool: Bash, when: [{field: command, match: x}], reason: r}]\n"
	type args struct {
		recordDir string
		content   string
	}
	type want struct {
		err error
		msg string
	}
	tcs := []struct {
		name string
		args args
		want want
	}{
		{
			"approved file of a relative record directory is an orphan",
			args{"rec", "# Generated by nodloop from the approved judgment knowledge of rec\n" + entry},
			want{file.ErrOrphan, "{path}: record directory \"rec\": " + file.ErrOrphan.Error()},
		},
		{
			"approved file of an absolute record directory is no orphan",
			args{"/records/", "# Generated by nodloop from the approved judgment knowledge of /records/\n" + entry},
			want{nil, "<nil>"},
		},
		{"approved file without a header is no orphan", args{"x", entry}, want{nil, "<nil>"}},
	}
	for _, tc := range tcs {
		t.Run(tc.name, func(t *testing.T) {
			t.Parallel()
			home := t.TempDir()
			path := file.NewApprovedFile(home, tc.args.recordDir).Path()
			require.NoError(t, os.MkdirAll(filepath.Dir(path), 0o700))
			require.NoError(t, os.WriteFile(path, []byte(tc.args.content), 0o600))
			sources, err := file.Discover("", home)
			require.NoError(t, err)
			require.Len(t, sources, 1)
			require.Len(t, sources[0].Vetoes, 1)

			err = sources[0].Orphan()

			assert.ErrorIs(t, err, tc.want.err)
			assert.Equal(t, strings.ReplaceAll(tc.want.msg, "{path}", path), fmt.Sprint(err))
		})
	}
}
